### ISSUE TITLE
Fixes to weighted_interval_score()

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/covidcast#393] opened 2020-12-29 22:29 UTC
On the evalcast-killcards branch, there's a few things bothering me about `weighted_interval_score()`.  First, I don't like that it will assign NAs for unsorted quantile values or quantile levels asymmetric around 0.5.  Neither of these seem necessary to me, because, recall, weighted interval score is exactly equivalent to quantile regression loss.  And these can be real impediments in practice because, fir example, a simple autoregressive quantile forecaster could indeed produce quantile predictions that are out of order (if we don't enforce noncrossing constraints) but I should still be able to score this.

Further, I don't find that the `weighted_interval_score()` function in evalcast matches the simple one I have below based on the equivalent quantile regression loss formulation:
```
weighted_interval_score <- function(tau, value, actual) {
  return(sum(pmax(
    tau * (actual - value), (tau - 1) * (actual - value)),
    na.rm = TRUE) / length(tau))
}
```
They're *close* (ish) but not exactly the same.  Something funny might be happening?

**Comment by dajmcdon** [comment] 2020-12-30 00:03
I think part of the issue is that when I changed probs --> quantile and quantiles --> value, I might have screwed up an `assert_that()`. As for the calculation being not quite the same, I'm not sure why that would be. Can you share an example?

Alternatively, we could replace the guts with your simple one and go from there.

**Comment by ryantibs** [comment] 2020-12-30 01:58
I struggled with this for a little while---the fact they weren't matching.  There was a constant factor difference but that wasn't what the problem was (they still weren't matching up to constants).  I figured it out: so in general, weighted interval score is actually *not* equivalent to quantile regression loss summed up over the given quantile levels!  

I've claimed that it was before in different places (perhaps even in the quantgen documentation, which builds ensembles to minimize quantile regression loss, so perhaps I claimed it also minimizes weighted interval score due to this equivalence).  But in fact weighted interval score counts the median *twice*, whereas the quantile loss will only count it once.  Meaning, the median basically gets a quantile loss term summed up twice in the total sum.  I think that's actually just a weird artifact of weighted interval score.  So if you just add another single absolute error term to the quantile regression loss sum, you get weighted interval score. 

The function below should now exactly match `evalcast::weighted_interval_score()`: 
```
weighted_interval_score <- function(tau, value, actual) {
  return((absolute_error(tau, value, actual) / 2) +
         sum(pmax(tau * (actual - value),
         (tau - 1) * (actual - value), na.rm = TRUE)) /
         (length(tau) + 1) * 2)
}
```
For example: 
```
> evalcast::weighted_interval_score(modeltools::covidhub_probs, 1:23, 10)
[1] 1.685
> weighted_interval_score(modeltools::covidhub_probs, 1:23, 10)
[1] 1.685
```

**Comment by dajmcdon** [comment] 2020-12-30 02:44
I see. So for a forecaster predicting only the median, WIS==AE.

That formula allows us to remove the symmetry checks and the checks for the number of values tau since we're no longer calculating "intervals" and their lengths. But we still need to ensure that there is a prediction at 0.5?

And a point forecaster (with quantile==NA and no others) should return NA it seems.

**Comment by dajmcdon** [comment] 2020-12-30 17:55
I can't replicate your result for some reason. What is your definition of `modeltools::covidhub_probs`? I did:

```r
ryans_weighted_interval_score <- function(tau, value, actual) {
  return((evalcast::absolute_error(tau, value, actual) / 2) +
               sum(pmax(tau * (actual - value),
               (tau - 1) * (actual - value), na.rm = TRUE)) /
               (length(tau) + 1) * 2)
}

covidhub_probs <- function() {
  c(0.01, 0.025, seq(0.05, 0.95, by = 0.05), 0.975, 0.99)
}
```

and got

```r
> ryans_weighted_interval_score(covidhub_probs(), 1:23, 10)
[1] 2.601667
> evalcast::absolute_error(covidhub_probs(), 1:23,10)
[1] 2
```

**Comment by ryantibs** [comment] 2020-12-30 20:56
Yep that's the right `covidhub_probs` vector. But I'm a bit confused by your last code chunk.  You mean to compare `ryans_weighted_interval_score()` against `evalcast::weighted_interval_score()` (not`evalcast::absolute_error()`)? 

In any case you should be getting 1.685 for `ryans_weighted_interval_score()`, so something's not matching.  I actually defined both absolute error and weighted interval score like so:
```
 absolute_error <- function(tau, value, actual) {
  return(abs(actual - value)[tau == 0.5])
}

weighted_interval_score <- function(tau, value, actual) {
  return((absolute_error(tau, value, actual) / 2 +
         sum(pmax(tau * (actual - value),
         (tau - 1) * (actual - value), na.rm = TRUE))) /
         (length(tau) + 1) * 2)
}
```
So you should be able to use this to reproduce what I got. So the culprit could be that my `absolute_error()` and `evalcast::absolute_error()` don't match?

**Comment by dajmcdon** [comment] 2020-12-30 21:09
Found it! The version you just gave has a parenthesis that is different from the earlier version. 😃 

Now it matches.

**Comment by ryantibs** [comment] 2020-12-31 02:20
Ugh, my bad. Maybe serves me right for copy-pasting code over GitHub comments.

**Comment by jacobbien** [comment] 2021-01-04 23:47
Per our conversation on slack, it seems we should move to
```
wis <- 2*mean(pmax(
              quantile * (actual_value - value),
              (1 - quantile) * (value - actual_value), 
              na.rm = TRUE))
```
The factor of 2 is to put this on the scale of interval scores (i.e. the average of 11.5 interval scores rather than the average of 23 quantiles).

**Comment by dajmcdon** [comment] 2021-01-05 00:01
This should be fixed by the most recent push. I'm going to leave this open for the moment just for reference.

**Closed** 2021-01-08 15:56 UTC
Labels: evalcast package
