### ISSUE TITLE
get_covidhub_predictions is very slow

### ISSUE THREAD

**Issue by JedGrabman** [cmu-delphi/covidcast#280] opened 2020-11-13 22:49 UTC
`get_covidhub_predictions` is very slow currently. 

I would describe the format of the function currently as:
1. Retrieve .csv file from covidhub
2. Load .csv file
3. Rearrange data into cards
4. Filter cards

Surprisingly, most of our time is spent on processing the data (step 3) rather than retrieving it. Probably the easiest win is to do the filtering before we create the cards. Processing data for 3000+ counties is particularly inefficient when we are only interested in state level forecasts (~50 states).

This would mean not using `filter_predictions`, since the data formats are different. 

The other potential speedup is to improve our data processing. In particular, [`group_modify`](https://github.com/cmu-delphi/covidcast/blob/f9fbeb44ccfb74258912af18eeb267ee147ac3a0/R-packages/evalcast/R/get_covidhub_predictions.R#L63) seems quite slow, sometimes taking 20-25 seconds. My dplyr isn't good enough to say if there's a better way, perhaps this is an unavoidable consequence when processing thousands of counties, but it is certainly worth a closer look.

See also #223 for other issues related to `get_covidhub_predictions`

**Comment by jacobbien** [comment] 2020-11-13 23:58
That's an interesting observation that the slowest part is the processing!  I'm not sure what the performance of `group_modify` is like relative to other functions, but my guess is that it has to do, as you say, with loading all counties even when we just want states.  Note that this all might not be relevant since the intent is for `get_covidhub_predictions` to change once we use the new `covidHubUtils` package.  See [Ryan's comment](https://github.com/cmu-delphi/covidcast/issues/99#issuecomment-720704324) in #99.

**Comment by dajmcdon** [comment] 2020-11-16 19:10
It's possible that we don't want `get_covidhub_predictions()` (or its successor implemented with `covidHubUtils`) to create cards at all. The point of the cards (correct me if I'm wrong @jacobbien) is to track all attributes necessary for reproducing the forecasts. The cards avoid duplicating those attributes unnecessarily, which would explode the storage requirements (compare to duplicating the forecast date in a column next to every quantile). However, the covidhub predictions won't be reproduced, except perhaps by ensuring the right `as_of`. So we would want the workflow to be more dependent on what we want to do with them.

Suppose, for example, our goal is to compare them via `plot_trajectory()` with our own internal forecasts. Then we would do steps 1-4 above and then convert from cards back to a long tibble using `aggregate_cards()` (currently hard-coded into the plotting). So, we convert to cards, and then back from cards. On the other hand, completely ditching the cards would be dangerous without tracking the implications for the following analysis.

I'd suggest we add a reverse operation to #221 and try to call one or the other when necessary rather than always assuming that the input is cards (or long tibble).

**Comment by JedGrabman** [comment] 2020-11-18 15:24
>I'd suggest we add a reverse operation to #221 and try to call one or the other when necessary rather than always assuming that the input is cards (or long tibble).

I agree that reducing the amount of aggregation / deaggregation could improve performance, we would just need to be sure to do it in a way where we ensure we don't duplicate work. That is, if we returned a long tibble and needed cards, we wouldn't want to have to do that conversion multiple times if the user ends up making multiple calls to the function.

One option is to be stricter with data types, i.e. have functions only accept tibbles or cards and expose the conversion features to the user. Other options might be memoization of conversion functions or some sort of larger class that contains both formats, but those seem messier.

**Comment by jacobbien** [comment] 2020-11-18 17:50
It sounds to me based on Jed’s initial message that the biggest issue might
be manipulating all counties when in fact we only care about states. But
might this be resolved by using the new R package from the Reich lab for
covid hub access? It’s likely (I’m guessing) that this function may return
something akin to the long tibble, so then Dan’s suggestion to return the
long tibble may indeed speed things up. However for a fair bit of the other
functions in evalcast users would then need to the the conversion to cards
themselves, which might be a bit inconvenient.

**Comment by dajmcdon** [comment] 2020-11-18 18:38
1. It's possible that using the Reich Lab package will help, but that still may be longer term.

2. Short term, what happens if we just filter by the `...` argument first rather than last? @JedGrabman can you try implementing this? It may help also to do it as an intermediate assignment rather then chained with all the other processing from [line 52](https://github.com/cmu-delphi/covidcast/blob/09371459a9e1e13e647d93d63423b15e8a85889b/R-packages/evalcast/R/get_covidhub_predictions.R#L52) to [line 88](https://github.com/cmu-delphi/covidcast/blob/09371459a9e1e13e647d93d63423b15e8a85889b/R-packages/evalcast/R/get_covidhub_predictions.R#L88) (maybe not, I'm not sure how dplyr handles chained functions like this).

3. A more elaborate fix would be not aggregating/disaggregating cards until necessary. Since the cards have classes now, we could also create a class for the long tibble (aggregated) version. Then we would convert from one to the other only when necessary. Or even better, have generics that handle either case and the associated methods would dispatch to avoid conversions where possible. This would require writing two versions of most functions which would be a pain.

**Comment by JedGrabman** [comment] 2020-11-23 14:45
It looks like we make use of `filter_predictions` to do the filtering at the end, which I believe requires we already have an object that's a predictions_card. I can look into moving the filtering earlier, but I'm not quite sure what form that will take since I haven't worked much with ellipsis arguments.

**Comment by JedGrabman** [comment] 2020-12-04 19:56
This probably needs to be revisited since we're getting rid of cards, so that may substantially speed up the process.

However, we should still consider filtering. The results can balloon quite fast for county level forecasts (3k counties * 24 quantiles * 2 types (cases + deaths) * 4 aheads > 500K rows for some forecasters per date. It can be filtered after it's returned, but it would be a user friendly improvement if we could allow them to specify what they want. We'd probably want to internally memoize the data retrieval, in case a user ends up realizing they wanted something different than what they first said.

**Comment by ryantibs** [comment] 2020-12-04 20:10
I may be missing something here but why are we even implementing this ourselves anymore?  covidHubUtils provides the functionality we need.  And it's based on querying the Zoltar API (through the zoltr R package) so it's about as fast as you can get (my understanding).

Nick & co specifically rewrote functionality in covidHubUtils / zoltr to allow direct querying of COVID Hub forecasts without a Zoltar account, at my request, so it's good-to-go for us to use.  You can see how it's used by checking out my [CFR analysis](https://htmlpreview.github.io/?https://github.com/cmu-delphi/covidcast-modeling/blob/cfr-analysis/cfr_analysis/cfr_analysis.html#Ensemble_comparison) (first code chunk in the last section).

And lastly, Dan's design of our long data frames was meant to adhere as closely as possible to covidHubUtils' structure, so minimum processing should be needed to convert the latter's format to our format.

So unless I'm missing something, we shouldn't be implementing anything at all on our side and just creating a wrapper function around `covidHubUtils::load_forecasts()`?

**Comment by dajmcdon** [comment] 2020-12-08 00:17
Done. Both the Zoltar and the old version are now available.

**Closed by dajmcdon** 2020-12-08 00:17 UTC
Labels: evalcast package
